name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Uploader
      uses: actions/checkout@v3
      with:
        repository: uj-master-thesis/Uploader
        path: Uploader
    - name: Checkout Gateway
      uses: actions/checkout@v3
      with:
        repository: uj-master-thesis/Gateway
        path: Gateway
    - name: Checkout Inventory
      uses: actions/checkout@v3
      with:
        repository: uj-master-thesis/Inventory
        path: Inventory

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        build-root-directory: ./Uploader
    - name: Build the stack
      run: docker-compose -f ./Uploader/docker-compose.yml up --build
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    - name: execute Tests
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install requests
        python -m pytest ./Gateway/ReditEndToEntTests.py
